baselineDescription="FlywayBaseline"
encoding="UTF-8"
environment="default"
ignoreMigrationPatterns=["*:future"]
locations=["db/migration"]
placeholderPrefix="${"
placeholderReplacement=true
placeholderSeparator=":"
placeholderSuffix="}"
provisionMode="provision"
repeatableSqlMigrationPrefix="R"
reportFilename="report"
scriptPlaceholderPrefix="FP__"
scriptPlaceholderSuffix="__"
sqlMigrationPrefix="V"
sqlMigrationSeparator="__"
sqlMigrationSuffixes=[".sql"]
table="flyway_schema_history"
target="latest"
environments.tempConfigEnvironment.jdbcProperties={}
environments.tempConfigEnvironment.schemas=["flyway"]

group=true
validateMigrationNaming=true
environments.default.jdbcProperties={}
environments.default.schemas=["flyway"]
baselineOnMigrate=false
batch=false
callbacks=[]
cleanDisabled=true
cleanOnValidationError=false
communityDBSupportEnabled=true
createSchemas=true
detectEncoding=false
errorOverrides=[]
executeInTransaction=true
failOnMissingLocations=false
failOnMissingTarget=false

jarDirs=[]
lockRetryCount=50
migrationResolvers=[]
mixed=false
outOfOrder=false
outputProgress=false
outputQueryResults=true
reportEnabled=false
skipDefaultCallbacks=false
skipDefaultResolvers=false
skipExecutingMigrations=false
stream=false
validateOnMigrate=true
